import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { iranSans } from "@/lib/utils";
import Header from "@/components/navigation/header/header";
import Footer from "@/components/navigation/footer/footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${outfit.variable} ${iranSans.className} antialiased bg-slate-50 max-w-[1920px] mx-auto overflow-x-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
